# Generated by Django 5.2.5 on 2025-08-30 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="created_by",
            field=models.CharField(max_length=150),
        ),
    ]
